# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

# Require a recent version of vagrant otherwise some have reported errors setting host names on boxes
Vagrant.require_version ">= 1.6.2"

if ENV['MASTER_IP'].to_s == ""
  raise Vagrant::Errors::VagrantError.new, <<END
Unable to start minions without master ip address, please set MASTER_IP env variable.
END
end


$num_minion = (ENV['NUM_MINIONS'] || 1).to_i
$vm_mem_size = (ENV['MEM_SIZE'] || "4096").to_i
$master_ip = (ENV['MASTER_IP']).to_s

Vagrant.configure(2) do |config|
 $num_minion.times do |n|
  minion_vm_name = "minion-#{n+1}"
  config.ssh.insert_key = false
  config.vm.define minion_vm_name do |minion|
    minion.vm.synced_folder "../salt/", "/srv/"
    minion.vm.synced_folder ".", "/vagrant"
    if ENV['NETWORK_TYPE'].to_s == "" then
      minion.vm.network "public_network"
    end
    if ENV['NETWORK_TYPE'].to_s == "private"
      minion.vm.network "private_network", type: "dhcp"
    end
    minion.vm.provision "shell" do |s|
      s.inline = "echo -e master_ip: $1 >> /etc/salt/grains;echo -e nfs_ip: $1 >> /etc/salt/grains"
      s.args = $master_ip
    end
    minion.vm.provider :virtualbox do |v, override|
      override.vm.box = (ENV['BOX_NAME'] || "dekstroza/kube-overlay-zfs").to_s
      override.vbguest.auto_update = false
      v.memory = $vm_mem_size
      v.cpus = $vm_cpus
      disk_file_name = '.tmp/'+ minion_vm_name +'/disk2.vdi'
      v.customize ["modifyvm", :id, "--nictype1", "virtio"]
      v.customize ["modifyvm", :id, "--nictype2", "virtio"]
      v.customize ["modifyvm", :id, "--cableconnected1", "on"]
      v.customize ["modifyvm", :id, "--cableconnected2", "on"]
      v.customize ['createhd', '--filename', disk_file_name, '--size', 500 * 1024]
      v.customize ["storagectl", :id, "--name", "SATA Controller", "--add", "sata", "--hostiocache", "on"]
      v.customize ["storageattach", :id, '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', disk_file_name]
      override.vm.provision :shell, :inline => (%q{
       echo -e "roles:\n  - kube-minion" >> /etc/salt/grains
       /usr/sbin/ifconfig eth0 down && /usr/bin/sleep 2 && /usr/sbin/ifconfig eth0 up
       salt-call state.highstate -l quiet
       echo "#################################################################################"
       echo "# Please create route to your cloud by running:                                 #"
       echo "# 1. For MacOS, please run:   add-route-osX.sh                                  #"
       echo "# 2. For Linux, please run:   add-route-LIN.sh                                  #"
       echo "# 3. For Windows, please run: add-route-WIN.bat                                 #"
       echo "#                                                                               #"
       echo "#             SSH into machine with vagrant ssh command                         #"
       echo "#                         ~Have fun, Dejan~                                     #"
       echo "#################################################################################"
       exit
       }).strip
    end
    
    minion.vm.provider :parallels do |v, override|
      override.vm.box = (ENV['BOX_NAME'] || "dekstroza/kube-overlay-zfs").to_s
      v.memory = $vm_mem_size
      v.cpus = $vm_cpus
      # Don't attempt to update the Parallels tools on the image (this can
      # be done manually if necessary)
      v.update_guest_tools = false

      # Set up Parallels folder sharing to behave like VirtualBox (i.e.,
      # mount the current directory as /vagrant and that's it)
      v.customize ['set', :id, '--shf-guest', 'off']
      v.customize ['set', :id, '--shf-guest-automount', 'off']
      v.customize ['set', :id, '--shf-host', 'on']
      v.customize ['set', :id, '--device-add', 'hdd']
      # Remove all auto-mounted "shared folders"; the result seems to
      # persist between runs (i.e., vagrant halt && vagrant up)
      override.vm.provision :shell, :inline => (%q{
        if [ -d /media/psf ]; then
          for i in /media/psf/*; do
            if [ -d "${i}" ]; then
              (umount "${i}" || true) > /dev/null 2>&1
              rmdir -v "${i}" > /dev/null 2>&1
            fi
          done
          rmdir -v /media/psf > /dev/null 2>&1
        fi
        echo -e "roles:\n  - kube-minion" >> /etc/salt/grains
        /usr/sbin/ifconfig eth0 down && /usr/bin/sleep 2 && /usr/sbin/ifconfig eth0 up
        salt-call state.highstate -l quiet
        echo "#################################################################################"
        echo "# Please create route to your cloud by running:                                 #"
        echo "# 1. For MacOS, please run:   add-route-osX.sh                                  #"
        echo "# 2. For Linux, please run:   add-route-LIN.sh                                  #"
        echo "# 3. For Windows, please run: add-route-WIN.bat                                 #"
        echo "#                                                                               #"
        echo "#             SSH into machine with vagrant ssh command                         #"
        echo "#                         ~Have fun, Dejan~                                     #"
        echo "#################################################################################" 
        exit
      }).strip
    end
  end
 end




# Give access to all physical cpu cores
# Previously cargo-culted from here:
# http://www.stefanwrobel.com/how-to-make-vagrant-performance-not-suck
# Rewritten to actually determine the number of hardware cores instead of assuming
# that the host has hyperthreading enabled.
host = RbConfig::CONFIG['host_os']
if host =~ /darwin/
  $vm_cpus = `sysctl -n hw.physicalcpu`.to_i
elsif host =~ /linux/
  #This should work on most processors, however it will fail on ones without the core id field.
  #So far i have only seen this on a raspberry pi. which you probably don't want to run vagrant on anyhow...
  #But just in case we'll default to the result of nproc if we get 0 just to be safe.
  $vm_cpus = `cat /proc/cpuinfo | grep 'core id' | sort -u | wc -l`.to_i
  if $vm_cpus < 1
      $vm_cpus = `nproc`.to_i
  end
else # sorry Windows folks, I can't help you
  $vm_cpus = 4
end
end

