heat_template_version: 2015-04-30
description: Kubernetes cluster heat template - Dejan Kitic 2016

parameters:
  image:
    type: string
    description: Image used for servers

  kube-minion-flavour:
    type: string
    description: Flavour used for kubernetes worker nodes

  network-name:
    type: string
    description: Name of the network used in VM instances

  server_ssh_key:
    type: string
    description: SSH key used to connect to worker nodes

  docker_vol_size:
    type: number
    description: Size of the cinder volume used for docker images

  master_ip:
    type: string
    description: IP Address of kubernetes master
  metadata:
    type: json

  auth-url:
    type: string
    description: Keystone authentication url

  username:
    type: string
    description: Username for Keystone authentication

  password:
    type: string
    description: Password for Keystone authentication

  region:
    type: string
    description: Region of this tenant

  tenant-id:
    type: string
    description: Tenant id
resources:
  minion-node:
    type: OS::Nova::Server
    properties:
      image: { get_param: image }
      flavor: { get_param: kube-minion-flavour }
      key_name: { get_param: server_ssh_key }
      metadata: {get_param: metadata}
      networks:
        - network: { get_param: network-name }
      user_data:
       str_replace:
        template: |
         #!/bin/bash
         echo "Running boot configuration script"
         cur_dir=$(pwd) && cd /opt/kubernetes-dev-stack && git pull && cd $cur_dir
         echo -e "roles:\n  - kube-minion" >> /etc/salt/grains
         echo -e master_ip: $mip >> /etc/salt/grains && echo -e nfs_ip: $mip >> /etc/salt/grains
         echo -e short_hostname: $(hostname -s) >> /etc/salt/grains
         mkdir /etc/kubernetes
         echo -e "[Global]" >> /etc/kubernetes/cloud.conf
         echo -e "auth-url=$auth-url" >> /etc/kubernetes/cloud.conf
         echo -e "username=$username" >> /etc/kubernetes/cloud.conf
         echo -e "password=$password" >> /etc/kubernetes/cloud.conf
         echo -e "region=$region" >> /etc/kubernetes/cloud.conf
         echo -e "tenant-id=$tenant-id" >> /etc/kubernetes/cloud.conf
         salt-call state.highstate -l quiet
        params:
         $mip: { get_param: master_ip }
         $auth-url: { get_param: auth-url }
         $username: { get_param: username }
         $password: { get_param: password }
         $region: { get_param: region }
         $tenant-id: { get_param: tenant-id }

  docker_vol:
    type: OS::Cinder::Volume
    properties:
      size: { get_param: docker_vol_size }

  docker_vol_att:
    type: OS::Cinder::VolumeAttachment
    properties:
      instance_uuid: { get_resource: minion-node }
      volume_id: { get_resource: docker_vol }
      mountpoint: /dev/vdb

