heat_template_version: 2015-04-30
description: Kubernetes cluster heat template - Dejan Kitic 2016

parameters:
  image:
    type: string
    description: Image used for servers

  kube-minion-flavour:
    type: string
    description: Flavour used for kubernetes worker nodes

  network-name:
    type: string
    description: Name of the network used in VM instances

  server_ssh_key:
    type: string
    description: SSH key used to connect to worker nodes

  docker_vol_size:
    type: number
    description: Size of the cinder volume used for docker images

  master_ip:
    type: string
    description: IP Address of kubernetes master
  metadata:
    type: json
resources:
  minion-node:
    type: OS::Nova::Server
    properties:
      image: { get_param: image }
      flavor: { get_param: kube-minion-flavour }
      key_name: { get_param: server_ssh_key }
      metadata: {get_param: metadata}
      networks:
        - network: { get_param: network-name }
      user_data:
       str_replace:
        template: |
         #!/bin/bash
         echo "Running boot configuration script"
         cur_dir=$(pwd) && cd /opt/kubernetes-dev-stack && git pull && cd $cur_dir
         echo -e "roles:\n  - kube-minion" >> /etc/salt/grains
         echo -e master_ip: $mip >> /etc/salt/grains && echo -e nfs_ip: $mip >> /etc/salt/grains
         salt-call state.highstate -l quiet
         yum -y install socat
        params:
         $mip: { get_param: master_ip }

  docker_vol:
    type: OS::Cinder::Volume
    properties:
      size: { get_param: docker_vol_size }

  docker_vol_att:
    type: OS::Cinder::VolumeAttachment
    properties:
      instance_uuid: { get_resource: minion-node }
      volume_id: { get_resource: docker_vol }
      mountpoint: /dev/vdb

