{% set heapster_memory = "300Mi" -%}
{% if pillar['num_nodes'] is defined -%}
  {% set heapster_memory = (200 + pillar['num_nodes'] * 12)|string + "Mi" -%}
{% endif -%}
{% set master_ip = salt['grains.get']('master_ip') %}

apiVersion: v1
kind: ReplicationController
metadata:
  name: heapster-v1.2.0
  namespace: kube-system
  labels:
    k8s-app: heapster
    version: v1.2.0
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: heapster
    version: v1.2.0
  template:
    metadata:
      labels:
        k8s-app: heapster
        version: v1.2.0
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
        - image: gcr.io/google_containers/heapster:v1.2.0
          name: heapster
          resources:
            limits:
              cpu: 100m
              memory: {{ heapster_memory }}
          command:
            - /heapster
            - --source=kubernetes:http://{{ master_ip }}:8080?inClusterConfig=false&insecure=true&auth=
            - --sink=influxdb:http://monitoring-influxdb:8086

